### ISSUE TITLE
No Celery service on docker-compose.yml

### ISSUE THREAD

**Issue by moracabanas** [jearistiz/guane-intern-fastapi#43]
## Steps

`git clone https://github.com/jearistiz/guane-intern-fastapi`  
`cd guane-intern-fastapi`  
`docker-compose up --build`  

## Expected behaviour
Docker compose starts building all service images from `docker-compose.yml`

## Actual behaviour

```
$ docker-compose up -d
ERROR: Service 'backend_app' depends on service 'celery' which is undefined.
```

So there is something I am missing or there is no celery service in `docker-compose.yml` which is required on `backend-app` service to work.
See `depends-on`:
```yaml
version: "3.5"
services:
  backend_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_app
    stop_signal: SIGINT
    env_file: .env
    image: app/backend
    depends_on: 
      - postgres
      - celery
. . .
```
